# Generated by Django 5.1.7 on 2025-03-27 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='units',
            field=models.ManyToManyField(through='inventory.ProductUnit', to='inventory.unit'),
        ),
    ]
