# Generated by Django 5.1.7 on 2025-04-03 01:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversion_factor', models.FloatField()),
                ('materialId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='material_app.material')),
                ('unitId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='material_app.unit')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialTransactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('base_quantity', models.FloatField()),
                ('transaction_type', models.CharField(choices=[('import', 'Nhập'), ('export', 'Xuất')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('materialId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='material_app.material')),
                ('unitId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='material_app.unit')),
            ],
        ),
        migrations.AddField(
            model_name='material',
            name='base_unitId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_materials', to='material_app.unit'),
        ),
        migrations.AddField(
            model_name='material',
            name='units',
            field=models.ManyToManyField(through='material_app.MaterialUnit', to='material_app.unit'),
        ),
    ]
