# Generated by Django 5.1.7 on 2025-04-16 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='inventory_level',
            field=models.FloatField(default=0.0, editable=False, verbose_name='Tồn kho (ĐV cơ bản)'),
        ),
    ]
