# Generated by Django 5.1.7 on 2025-04-19 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material_app', '0002_material_inventory_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='base_unitId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='base_materials', to='material_app.unit'),
        ),
        migrations.AlterField(
            model_name='material',
            name='inventory_level',
            field=models.FloatField(default=0.0, verbose_name='Tồn kho (ĐV cơ bản)'),
        ),
        migrations.AlterField(
            model_name='materialtransactions',
            name='unitId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='material_app.unit'),
        ),
        migrations.AlterField(
            model_name='materialunit',
            name='unitId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='material_app.unit'),
        ),
    ]
